{
 "title": "TrackFlow",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total Orders Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{application=\"order-service\", uri=\"/api/v1/orders\", method=\"POST\", outcome=\"SUCCESS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Notifications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{project=\"trackflow\", application=\"notification-service\", outcome=\"SERVER_ERROR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{project=\"trackflow\", outcome=~\"CLIENT_ERROR|SERVER_ERROR\"}[1m])",
     "legendFormat": "{{application}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Service Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"order-service\"}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{project=\"trackflow\", area=\"heap\"}",
     "legendFormat": "{{application}} - {{id}}"
    }
   ]
  }
 ]
}